class BaseEvaluator:
    """
    Base class for all evaluators. Defines the common interface that all evaluators must implement.
    """

    def __init__(self):
        """
        Initialize the base evaluator.
        """
        self.name = "base_evaluator"

    def evaluate(self, input_text, model_output, ground_truth, config):
        """
        Evaluate the model output based on the input and ground truth.

        Args:
            input_text (str): The original input prompt or context provided to the model
            model_output (str): The response generated by the model
            ground_truth (str): The expected or reference output/answer
            config (dict): Additional configuration parameters for evaluation

        Returns:
            float: Score between 0.0 and 1.0 indicating evaluation performance

        Raises:
            NotImplementedError: This method must be implemented by subclasses
        """
        raise NotImplementedError("Subclasses must implement the evaluate method")